[templates.advskcolorscheme]
input_path = 'SHELL_DIR/matugen/templates/kcolorscheme.colors'
output_path = 'DATA_DIR/color-schemes/AdvMatugen.colors'

[templates.advslightkcolorscheme]
input_path = 'SHELL_DIR/matugen/templates/light-kcolorscheme.colors'
output_path = 'DATA_DIR/color-schemes/AdvMatugenLight.colors'

[templates.advsdarkkcolorscheme]
input_path = 'SHELL_DIR/matugen/templates/dark-kcolorscheme.colors'
output_path = 'DATA_DIR/color-schemes/AdvMatugenDark.colors'
