[templates.advskitty]
input_path = 'SHELL_DIR/matugen/templates/kitty.conf'
output_path = 'CONFIG_DIR/kitty/adv-theme.conf'

[templates.advskittytabs]
input_path = 'SHELL_DIR/matugen/templates/kitty-tabs.conf'
output_path = 'CONFIG_DIR/kitty/adv-tabs.conf'
