background = {{colors.background.default.hex}}
foreground = {{colors.on_surface.default.hex}}
cursor-color = {{colors.primary.default.hex}}
selection-background = {{colors.primary_container.default.hex}}
selection-foreground = {{colors.on_surface.default.hex}}

palette = 0={{adv16.color0.default.hex}}
palette = 1={{adv16.color1.default.hex}}
palette = 2={{adv16.color2.default.hex}}
palette = 3={{adv16.color3.default.hex}}
palette = 4={{adv16.color4.default.hex}}
palette = 5={{adv16.color5.default.hex}}
palette = 6={{adv16.color6.default.hex}}
palette = 7={{adv16.color7.default.hex}}
palette = 8={{adv16.color8.default.hex}}
palette = 9={{adv16.color9.default.hex}}
palette = 10={{adv16.color10.default.hex}}
palette = 11={{adv16.color11.default.hex}}
palette = 12={{adv16.color12.default.hex}}
palette = 13={{adv16.color13.default.hex}}
palette = 14={{adv16.color14.default.hex}}
palette = 15={{adv16.color15.default.hex}}
