[colors]
background = '{{colors.background.default.hex}}'
foreground = '{{colors.on_surface.default.hex}}'

cursor_bg = '{{colors.primary.default.hex}}'
cursor_fg = '{{colors.background.default.hex}}'
cursor_border = '{{colors.primary.default.hex}}'

selection_bg = '{{colors.primary_container.default.hex}}'
selection_fg = '{{colors.on_surface.default.hex}}'

ansi = ['{{adv16.color0.default.hex}}', '{{adv16.color1.default.hex}}', '{{adv16.color2.default.hex}}', '{{adv16.color3.default.hex}}', '{{adv16.color4.default.hex}}', '{{adv16.color5.default.hex}}', '{{adv16.color6.default.hex}}', '{{adv16.color7.default.hex}}']
brights = ['{{adv16.color8.default.hex}}', '{{adv16.color9.default.hex}}', '{{adv16.color10.default.hex}}', '{{adv16.color11.default.hex}}', '{{adv16.color12.default.hex}}', '{{adv16.color13.default.hex}}', '{{adv16.color14.default.hex}}', '{{adv16.color15.default.hex}}']
